### ISSUE TITLE
`wb_supervisor_node_get_field_by_index` not working

### ISSUE THREAD

**Issue by Justin-Fisher** [cyberbotics/webots#4363]
`wb_supervisor_node_get_field_by_index` sometimes returns an incorrect field.  

**Short version:** at least in some cases, if I use `wb_supervisor_node_get_field_by_index` to get the field with index `a` from the node with id `b`, and then try to use it to get the field with index `b` from the node with id `a`, it wrongly returns that first field again, rather than correctly returning a different field.  So probably you somewhere have variables for a node id and a field index swapped, probably in a case where you're trying to check if a field had already been accessed so that you could return the same field handler again.  Hopefully that will help you to debug it!?  

**Longer version:** (Heavily edited now that I have a better sense of what's happening.)

Here's some bare-bones Python code that consistently reproduces this for me, in a world with the controller's robot having node `id 8`.  While the commented-out line remains commented out, or even if its index is changed from 8 (the `FPS` field) to any other index, then the final line correctly prints that, in the `self` robot, the field with index 1 is a `rotation` field'; whereas if that line is uncommented with index 8, so it accesses the `FPS` field of `WorldInfo` (node id 1) first, then, for some reason, the next-to-last line mistakenly returns that same pointer for the FPS field again, and hence the final line incorrectly reports that the robot's rotation field is named `FPS`.  

This wire-crossing is apparently confusing Node id 8 Field index 1 with Node id 1 Field index 8.  Similarly, another wire-crossing I noticed (between the robot's `children` field and a contact-properties `softCFM` field) is apparently between Node id 8 Field index 3 and Node id 3 Field index 8.  So probably you somewhere have variables for a node id and a field index swapped, probably in a case where you're trying to check if a field had already been accessed.  

```python
    from ctypes import CDLL, c_void_p, c_char_p
    class Ref(c_void_p): pass
    wb = CDLL(r"D:\Program Files\Webots\lib\controller\Controller")
    wb.wb_robot_init()
    wb.wb_supervisor_node_get_from_id.restype = Ref
    wb.wb_supervisor_node_get_self.restype = Ref
    wb.wb_supervisor_node_get_field_by_index.restype = Ref
    wb.wb_supervisor_field_get_name.restype = c_char_p
    world_info = wb.wb_supervisor_node_get_from_id(1)
    self = wb.wb_supervisor_node_get_self()
    # FPS_field = wb.wb_supervisor_node_get_field_by_index(world_info, 8) # uncommenting this fubars getting the rotation field
    rotation_field = wb.wb_supervisor_node_get_field_by_index(self, 1)
    print( wb.wb_supervisor_field_get_name(rotation_field) )
```

**Comment by Justin-Fisher** [comment]
Okay, I poked around in `supervisor.c`, and it looks like this is indeed a simple case of switching field `index` and `node->id`.  The following lines in `wb_supervisor_node_get_field_by_index` both provide arguments in the order `index`, `node->id`

> 2305:  [WbFieldRef result = find_field_by_id(index, node->id);](https://github.com/cyberbotics/webots/blob/f5ae03cbfb535553ab7870963a3f3479e913c2a8/src/controller/c/supervisor.c#L2305)
> 2316:  [result = find_field_by_id(index, node->id);](https://github.com/cyberbotics/webots/blob/f5ae03cbfb535553ab7870963a3f3479e913c2a8/src/controller/c/supervisor.c#L2316)

However the definition of `find_field_by_id` instead expects the arguments to be ordered `node_id`, `field_id`.

>188: [static WbFieldStruct *find_field_by_id(int node_id, int field_id) {](https://github.com/cyberbotics/webots/blob/f5ae03cbfb535553ab7870963a3f3479e913c2a8/src/controller/c/supervisor.c#L188)

So it looks like the fix is probably just swapping the argument order in the first two lines linked above?

**Comment by omichel** [comment]
Well spotted! Can you please submit a [PR](https://github.com/cyberbotics/webots/edit/master/src/controller/c/supervisor.c#L2305) for patching this?

**Comment by Justin-Fisher** [comment]
I'm not great at doing PR's through the Github editor (nor perhaps in any other way), but think I have successfully done so here: [https://github.com/cyberbotics/webots/pull/4366](https://github.com/cyberbotics/webots/pull/4366) 

NOTE:  I'm not set up to re-compile Webots C code, so **I DID NOT TEST THIS!!!**  Someone should compile and test it!

**Comment by omichel** [comment]
> NOTE: I'm not set up to re-compile Webots C code, so I DID NOT TEST THIS!!! Someone should compile and test it!

It is pretty easy to compile Webots from the sources by following [these instructions](https://github.com/cyberbotics/webots/wiki). This will save you a lot of time when investigating this kind of problems.

**Comment by Justin-Fisher** [comment]
Almost all of my C-coding experience is from the last millennium, so I'm not the right person to take this on.  (And reading this C code reminds me of why I like Python so much better, since C wastes countless lines doing stuff that Python takes care of automatically!)  I did skim through `supervisor.c` looking at all the uses of `field_list` and couldn't find any other place where correcting the order of arguments to `find_field_by_id` should matter.  The code definitely looked wrong before, comparing node id's to field indices and vice versa, and that fits with my observing that it returned mistaken field references that were swapped in exactly this way.  But if fixing that problem causes some other problems (as your note in the PR's thread seems to suggest), then I'm not the right person to try to sort this out...  

(My guess would be that the reason it sort of seemed to work before was that, when you repeatedly got the same field by index, it actually kept not being able to find that field in `field_list` (line 2341) so it kept bloating `field_list` with additional copies, which is obviously suboptimal, but might easily appear to work.  If preventing it from bloating the list in this way is breaking things, then I'd suggest looking closely at lines 2343-2356, which are supposed to generate the new `field_list` entry in cases where the old field couldn't be found, which it usually *couldn't* when it was trying to look it up under swapped id-vs-index.  I don't fully understand this block of code, but maybe it was effectively doing something else that needed to be done too, that now gets skipped when it successfully finds the old field?  You might also wonder whether whatever test it's failing is right, if the test was built around mistaken code?)

Anyway, it'd be nice if you could get it fixed though, because right now `wb_supervisor_get_field_by_index` is very risky to use, since the more nodes you use it on, the greater the risk it'll get its wires crossed and start returning fields from some other node instead.  It's likely also inefficient due to list-bloating, and will get more and more inefficient the more you use it, since lookup time is going to scale up `O(n)` as the list bloats. I'd been hoping to use `get_field_by_index` to systematically introspect the whole scene tree in a controller, but that use is currently impossible, since accessing Node N field F currently prevents later access to Node F Field N, and vice versa.  I guess for now, I'll need to go back to my old approach of looking up fields by name, rather than index...

**Comment by omichel** [comment]
> Anyway, it'd be nice if you could get it fixed though

Done.

**Comment by Justin-Fisher** [comment]
Hrmmm. I'd been hoping that installing the last nightly build would fix this, but after installing it, Webots won't start, saying "The code execution cannot proceed because libb2-1.dll was not found".  I've tried reinstalling, but that didn't fix it.  Are there additional steps that I'm missing?
